### ISSUE TITLE
 jsc3l.customization.getCurrencyLogoUrl()  return undefined values

### ISSUE THREAD

**Issue by FlorianDubath** [com-chain/JSC3L#5]
This is a timing problem: when the function is called and the underlying custo repo is not yet selected the returned url starts with "undefined".

The expected behavior should be a block of the execution until the value can be looked up into the selected repo

**Comment by vaab** [comment]
Thx for the feedback, this branch concerns branch `rc0`. This was corrected in commit 361895c ... the problem is that it is expected to be able to access some customization variables before the external configuration was actually fetched. But some elements will require anyway the configuration to be loaded.

The incriminated code is now throwing an exception and the dependant querying function are having a sane default behavior that mimick what was done before in JSC3L.
